[build]
  publish = "dist"
  functions = "netlify/functions"

[functions."kit-vault"]
  included_files = ["netlify/functions/kit-riservato/**"]

[functions."crm"]
  included_files = ["netlify/functions/kit-riservato/TOUCHandGO_Allin_One.html"]
